### ISSUE TITLE
plugin not loading in 1.4.6

### ISSUE THREAD

**Issue by ytjohn** [Antergos/nodebb-plugin-sso-auth0#8]
I installed auth0 plugin, but it is failing to load. Plugin version 2.0.0 and nodebb 1.4.6. 

```
  "_resolved": "https://registry.npmjs.org/nodebb-plugin-sso-auth0/-/nodebb-plugin-sso-auth0-2.0.0.tgz",
  "_shasum": "ba504c17baa9dbc31a0d5410c70c545fb0a68075",
  "_shrinkwrap": null,
  "_spec": "nodebb-plugin-sso-auth0@2.0.0",
```

```
Jun 04 18:54:07 web01 nodebb[1360]: 4/6 18:54:07 [18501] - info: Initializing NodeBB v1.4.6
Jun 04 18:54:09 web01 nodebb[1360]: 4/6 18:54:09 [18501] - info: [socket.io] Restricting access to origin: https://community.yourtech.us:*
Jun 04 18:54:10 web01 nodebb[1360]: 4/6 18:54:10 [18501] - error: /opt/nodebb/node_modules/nodebb-plugin-sso-auth0/library.js:78
Jun 04 18:54:10 web01 nodebb[1360]:         async _do_async( func, ...args ) {
Jun 04 18:54:10 web01 nodebb[1360]:               ^^^^^^^^^
Jun 04 18:54:10 web01 nodebb[1360]: SyntaxError: Unexpected identifier
Jun 04 18:54:10 web01 nodebb[1360]:     at createScript (vm.js:56:10)
Jun 04 18:54:10 web01 nodebb[1360]:     at Object.runInThisContext (vm.js:97:10)
Jun 04 18:54:10 web01 nodebb[1360]:     at Module._compile (module.js:542:28)
Jun 04 18:54:10 web01 nodebb[1360]:     at Object.Module._extensions..js (module.js:579:10)
Jun 04 18:54:10 web01 nodebb[1360]:     at Module.load (module.js:487:32)
Jun 04 18:54:10 web01 nodebb[1360]:     at tryModuleLoad (module.js:446:12)
Jun 04 18:54:10 web01 nodebb[1360]:     at Function.Module._load (module.js:438:3)
Jun 04 18:54:10 web01 nodebb[1360]:     at Module.require (module.js:497:17)
Jun 04 18:54:10 web01 nodebb[1360]:     at require (internal/module.js:20:19)
Jun 04 18:54:10 web01 nodebb[1360]:     at Object.Plugins.requireLibrary (/opt/nodebb/src/plugins.js:39:33)
Jun 04 18:54:10 web01 nodebb[1360]:     at registerHooks (/opt/nodebb/src/plugins/load.js:138:13)
Jun 04 18:54:10 web01 nodebb[1360]:     at /opt/nodebb/src/plugins/load.js:81:6
Jun 04 18:54:10 web01 nodebb[1360]:     at /opt/nodebb/node_modules/async/lib/async.js:718:13
Jun 04 18:54:10 web01 nodebb[1360]:     at async.forEachOf.async.eachOf (/opt/nodebb/node_modules/async/lib/async.js:233:13)
Jun 04 18:54:10 web01 nodebb[1360]:     at _parallel (/opt/nodebb/node_modules/async/lib/async.js:717:9)
Jun 04 18:54:10 web01 nodebb[1360]:     at Object.async.parallel (/opt/nodebb/node_modules/async/lib/async.js:731:9)
Jun 04 18:54:10 web01 nodebb[1360]: 4/6 18:54:10 [18501] - warn: [plugins] Unable to parse library for: nodebb-plugin-sso-auth0
```

**Comment by ytjohn** [comment]
If I uninstall and reinstall it, here is the output:

```
$ sudo -H -u nodebb npm install nodebb-plugin-sso-auth0
npm WARN deprecated react-addons-css-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use CSSTransitionGroup from 'react-transition-group' instead.
nodebb@1.4.6 /opt/nodebb
└─┬ nodebb-plugin-sso-auth0@2.0.0
  ├─┬ auth0-lock@10.16.0
  │ ├─┬ auth0-js@8.6.0
  │ │ ├── base64-js@1.2.0
  │ │ └── winchan@0.2.0
  │ ├── blueimp-md5@2.3.1
  │ ├─┬ fbjs@0.3.2
  │ │ ├── core-js@1.2.7
  │ │ ├─┬ loose-envify@1.3.1
  │ │ │ └── js-tokens@3.0.1
  │ │ ├── ua-parser-js@0.7.12
  │ │ └── whatwg-fetch@0.9.0
  │ ├─┬ idtoken-verifier@1.0.2
  │ │ └── crypto-js@3.1.9-1
  │ ├── immutable@3.8.1
  │ ├── jsonp@0.2.1
  │ ├── password-sheriff@1.1.0
  │ ├─┬ prop-types@15.5.10
  │ │ └─┬ fbjs@0.8.12
  │ │   ├─┬ isomorphic-fetch@2.2.1
  │ │   │ ├─┬ node-fetch@1.7.1
  │ │   │ │ └── encoding@0.1.12
  │ │   │ └── whatwg-fetch@2.0.3
  │ │   └── setimmediate@1.0.5
  │ ├─┬ react@15.5.4
  │ │ └── fbjs@0.8.12
  │ ├─┬ react-addons-css-transition-group@15.5.2
  │ │ └── fbjs@0.8.12
  │ ├─┬ react-dom@15.5.4
  │ │ └── fbjs@0.8.12
  │ └─┬ superagent@3.5.2
  │   ├── component-emitter@1.2.1
  │   ├── cookiejar@2.1.1
  │   └── formidable@1.1.1
  └─┬ passport-auth0@0.6.0
    └─┬ passport-oauth@1.0.0
      ├─┬ passport-oauth1@1.1.0
      │ └── oauth@0.9.15
      └── passport-oauth2@1.4.0
```

**Comment by lots0logs** [comment]
Node 7.10.x or later is required. Its marked as such in the package.json file but I guess npm doesnt enforce it :unamused:

**Comment by ytjohn** [comment]
Has this been tested with node 8.x? I upgraded to that and now I'm getting a new, blocking error.

```
Jun 04 21:12:33 web01 nodebb[31870]: Clustering enabled: Spinning up 1 process(es).
Jun 04 21:12:34 web01 nodebb[31870]: 4/6 21:12:34 [31882] - info: Initializing NodeBB v1.4.6
Jun 04 21:12:36 web01 nodebb[31870]: 4/6 21:12:36 [31882] - info: [socket.io] Restricting access to origin: https://community.yourtech.us:*
Jun 04 21:12:37 web01 nodebb[31870]: 4/6 21:12:37 [31882] - info: [plugins/spam-be-gone] Settings loaded
Jun 04 21:12:37 web01 nodebb[31870]: AUTH0 ERROR - ENO-011b: {}
Jun 04 21:12:37 web01 nodebb[31870]: 4/6 21:12:37 [31882] - error: [plugins] filter:auth.init,  undefined
Jun 04 21:12:37 web01 nodebb[31870]: 4/6 21:12:37 [31882] - error: filter:auth.init - plugin failure
Jun 04 21:12:37 web01 nodebb[31870]: 4/6 21:12:37 [31882] - error: An error has occurred. Please report this error to us and include the
Jun 04 21:12:37 web01 nodebb[31870]:                                 following error code in your report: ENO-011b.
Jun 04 21:12:37 web01 nodebb[31870]: [cluster] Child Process (31882) has exited (code: 0, signal: null)
Jun 04 21:12:37 web01 systemd[1]: nodebb.service: Service hold-off time over, scheduling restart.
Jun 04 21:12:37 web01 systemd[1]: Stopped NodeBB forum for Node.js..
Jun 04 21:12:37 web01 systemd[1]: Started NodeBB forum for Node.js..
```

**Comment by lots0logs** [comment]
No, I'm afraid not. 8.x is for nightly builds which are typically unstable. I don't recommend using the nightlies in any production environment.

**Comment by lots0logs** [comment]
That being said..I think that error is simply because you haven't filled in the auth0 details. Go to Admin>>Social Authenticiation>>Auth0 and configure it then restart nodebb.

**Comment by ytjohn** [comment]
Sorry for the delay. The problem is that I can't get the plugin to load, so I never get the menu in the first place. With 8.x and the auth0 plugin, it won't even start.  I'll try node 7.10 and see if I can get it to load.

**Comment by ytjohn** [comment]
Here's the steps I took:

 * made sure  nodebb-plugin-sso-auth0 was deactivated
 * uninstalled nodebb-plugin-sso-auth0
 * stopped nodebb
 * uninstalled nodejs
 * re-install nodejs as 7.10.0
 * started nodebb
 * install nodebb-plugin-sso-auth0
 * activated nodebb-plugin-sso-auth0 (no option in social auth menu yet)
 * restart nodebb
 * nodebb fails to start
 * attempt restart from command line, get the ENO-011b error again.
 
```
NodeBB v1.4.6 Copyright (C) 2013-2014 NodeBB Inc.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions.
For the full license, please visit: http://www.gnu.org/copyleft/gpl.html

Clustering enabled: Spinning up 1 process(es).

8/6 21:53:57 [7091] - info: Initializing NodeBB v1.4.6
8/6 21:53:58 [7091] - info: [socket.io] Restricting access to origin: https://community.yourtech.us:*
8/6 21:53:58 [7091] - info: [plugins/spam-be-gone] Settings loaded
AUTH0 ERROR - ENO-011b: {}
8/6 21:53:58 [7091] - error: [plugins] filter:auth.init,  undefined
8/6 21:53:58 [7091] - error: filter:auth.init - plugin failure
8/6 21:53:58 [7091] - error: An error has occurred. Please report this error to us and include the
				following error code in your report: ENO-011b.
[cluster] Child Process (7091) has exited (code: 0, signal: null)
```

Version output:

```
nodebb@web01:/opt/nodebb$ nodejs --version
v7.10.0
```

I did npm list [here](https://gist.github.com/ytjohn/2ceaae64f7c525fb55f955a6168c3516)

**Comment by ytjohn** [comment]
Thanks, that commit fixed the issue.
